### ISSUE TITLE
cachix-action failing

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/www.haskell.org#304]
The `cachix-action` action is failing, and that breaks our CI and deploy pipelines. Pinging our Nix expert @rebeccaskinner. Maybe @TikhonJelvis could help also.

We get

```
         … while evaluating the 'drvPath' attribute of a derivation
           at /nix/store/2xhmq8r9iwn448gir09j4qg95gjypsj4-source/default.nix:19:17:
             18|                 # TODO: we lie here so that Nix won't build it
             19|                 drvPath = builtins.storePath (builtins.getAttr outputName outputs);
               |                 ^
             20|               };
  
         error: store path 'acfsgbmlm31ijimwrd5g96sgh59lmlc7-cachix-1.7.4-bin' is not a valid derivation path
```

https://github.com/haskell-infra/www.haskell.org/actions/runs/9507732828/job/26220105513?pr=301

I thought that bumping the version might fix it, but that didn't work:

```
  error:
         … while evaluating the 'drvPath' attribute of a derivation
           at /nix/store/2xhmq8r9iwn448gir09j4qg95gjypsj4-source/default.nix:19:17:
             18|                 # TODO: we lie here so that Nix won't build it
             19|                 drvPath = builtins.storePath (builtins.getAttr outputName outputs);
               |                 ^
             20|               };
  
         error: store path 'acfsgbmlm31ijimwrd5g96sgh59lmlc7-cachix-1.7.4-bin' is not a valid derivation path
  /home/runner/work/_actions/cachix/cachix-action/v15/dist/main/index.js:1702
                  error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                          ^
  
  Error: The process '/usr/bin/bash' failed with exit code 1
      at ExecState._setResult (/home/runner/work/_actions/cachix/cachix-action/v15/dist/main/index.js:1702:25)
      at ExecState.CheckComplete (/home/runner/work/_actions/cachix/cachix-action/v15/dist/main/index.js:1685:18)
      at ChildProcess.<anonymous> (/home/runner/work/_actions/cachix/cachix-action/v15/dist/main/index.js:1579:27)
      at ChildProcess.emit (node:events:519:28)
      at maybeClose (node:internal/child_process:1105:16)
      at ChildProcess._handle.onexit (node:internal/child_process:305:5)
  
  Node.js v20.13.1
```

https://github.com/haskell-infra/www.haskell.org/actions/runs/9512381697/job/26220261063?pr=303

**Comment by rebeccaskinner** [comment]
I'm not immediately sure what's going on but I'll start digging into this today.
